version: '3.8'

services:
  dns_private:
    container_name: dns_private
    build:
      context: ./containers/dns/private
    restart: 'always'
    dns: 1.1.1.1
    networks:
      skynet:
        ipv4_address: 10.0.10.10

  dns_public:
    container_name: dns_public
    build:
      context: ./containers/dns/public
    restart: 'always'
    ports:
      - 127.0.0.1:53:53/udp
    dns: 1.1.1.1

  nginx:
    container_name: nginx
    build:
      context: ./containers/nginx
    restart: 'always'
    volumes:
      - ${REPOS_DIR:-./repos}:/repos
      - ./resources/ca:/ca
    ports:
      - 80:80
      - 443:443
    networks:
      skynet:
        ipv4_address: 10.0.10.69

  php80:
    container_name: php80
    build:
      context: ./containers/php/80
    restart: 'always'
    volumes:
      - ${REPOS_DIR:-./repos}:/repos
    working_dir: /repos
    networks:
      skynet:
        ipv4_address: 10.0.10.80
    dns: 10.0.10.10
    depends_on:
      - dns_private

  php74:
    container_name: php74
    build:
      context: ./containers/php/74
    restart: 'always'
    volumes:
      - ${REPOS_DIR:-./repos}:/repos
    working_dir: /repos
    networks:
      skynet:
        ipv4_address: 10.0.10.74
    dns: 10.0.10.10
    depends_on:
      - dns_private

  mailhog:
    container_name: mailhog
    build:
      context: ./containers/mailhog
    restart: 'always'
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      skynet:
        ipv4_address: 10.0.10.20

networks:
  skynet:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      config:
        - subnet: 10.0.10.0/24