#!/usr/bin/env bash

function stackHelp {
	echo ""
	echo "  Pillar help"
	echo ""
	echo "      help                                            Display this help information"
	echo "      build                                           Build up stack"
	echo "      rebuild                                         Bring down stack, removing volumes, and build back up"
	echo "      remove                                          Bring down stack, removing volumes"
	echo "      restart                                         Stop and start stack"
	echo "      stop                                            Stop stack"
	echo "      start                                           Start stack"
	echo "      terminal {container}                            Get a terminal in a given container"
	echo "      composer {script} {project} {container}         Get a terminal in a given container"
	echo ""
}

function stackKeys {
	sudo docker container exec php80 bash /root/keys.sh
    sudo docker container exec php74 bash /root/keys.sh
    sudo docker container exec node bash /root/keys.sh
    sudo docker container exec sysops bash /root/keys.sh
}

function buildStack {
	sudo docker-compose up -d --build
    stackKeys
}

function rebuildStack {
	sudo docker-compose down -v
    sudo docker-compose up -d --build
    stackKeys
}

function removeStack {
	sudo docker-compose down -v
}

function restartStack {
	sudo docker-compose down
    sudo docker-compose up -d
    stackKeys
}

function stopStack {
	sudo docker-compose down
}

function startStack {
	sudo docker-compose up -d
    stackKeys
}

function stackTerminal {
	sudo docker container exec -it -w /repos $1 bash -l
}

function stackComposer {
	sudo docker container exec -it -w /repos/$2 $3 composer $1
}

case $1 in

	help)
		stackHelp
		;;

	build)
		buildStack
		;;

	rebuild)
		rebuildStack
		;;

	remove)
		removeStack
		;;

	restart)
		restartStack
		;;

	stop)
		stopStack
		;;

	start)
		startStack
		;;

	terminal)
		stackTerminal "$2"
		;;

	composer)
		stackComposer "$2" "$3" "$4"
		;;

	*)
		stackHelp
		;;
esac