#!/usr/bin/env bash

function stackHelp {
	echo ""
	echo "  Dynamo DB helper command help"
	echo ""
	echo "      help                                                             Display this help information"
	echo "      create-table {table-name} {attribute-definitions} {key-schema}   Create a new table"
	echo "      delete-table {table-name}                                        Delete a table"
	echo "      list-tables                                                      List all tables"
	echo ""
}

function createTable {
  aws dynamodb create-table \
      --table-name $1 \
      --attribute-definitions $2 \
      --key-schema $3 \
      --billing-mode PAY_PER_REQUEST \
      --endpoint-url http://dynamodb:8000
}

function deleteTable {
  aws dynamodb delete-table \
      --table-name $1 \
      --endpoint-url http://dynamodb:8000
}

function listTables {
  aws dynamodb list-tables \
      --endpoint-url http://dynamodb:8000
}

case $1 in

	help)
		stackHelp
		;;

  create-table)
		createTable "$2" "$3" "$4"
		;;

  delete-table)
    deleteTable "$2"
    ;;

  list-tables)
    listTables
    ;;

	*)
		stackHelp
		;;
esac